name: Deploy storybook

on:
  push:
    paths-ignore:
      - '*.md'
      - '*.yml'
      - 'LICENSE'
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    name: GH-pages
    runs-on: ubuntu-latest
    steps:
      - uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        with:
          path: ./storybook-static
          build_command: npm run build:storybook
